-- USERS
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE users TO c2n_admin;
GRANT USAGE, SELECT ON SEQUENCE users_id_seq TO c2n_admin;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE users TO c2n_user;
GRANT USAGE, SELECT ON SEQUENCE users_id_seq TO c2n_user;


-- CATEGORIES
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE categories TO c2n_admin;
GRANT USAGE, SELECT ON SEQUENCE categories_id_seq TO c2n_admin;

GRANT SELECT ON TABLE categories TO c2n_user;


-- PRODUCTS
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE products TO c2n_admin;
GRANT USAGE, SELECT ON SEQUENCE products_id_seq TO c2n_admin;

GRANT SELECT ON TABLE products TO c2n_user;


-- REVIEWS
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE reviews TO c2n_admin;
GRANT USAGE, SELECT ON SEQUENCE reviews_id_seq TO c2n_admin;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE reviews TO c2n_user;
GRANT USAGE, SELECT ON SEQUENCE reviews_id_seq TO c2n_user;