-- USERS
REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLE users FROM c2n_admin;
REVOKE USAGE, SELECT ON SEQUENCE users_id_seq FROM c2n_admin;

REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLE users FROM c2n_user;
REVOKE USAGE, SELECT ON SEQUENCE users_id_seq FROM c2n_user;

-- CATEGORIES
REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLE categories FROM c2n_admin;
REVOKE USAGE, SELECT ON SEQUENCE categories_id_seq FROM c2n_admin;

REVOKE SELECT ON TABLE categories FROM c2n_user;

-- PRODUCTS
REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLE products FROM c2n_admin;
REVOKE USAGE, SELECT ON SEQUENCE products_id_seq FROM c2n_admin;

REVOKE SELECT ON TABLE products FROM c2n_user;

-- REVIEWS
REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLE reviews FROM c2n_admin;
REVOKE USAGE, SELECT ON SEQUENCE reviews_id_seq FROM c2n_admin;

REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLE reviews FROM c2n_user;
REVOKE USAGE, SELECT ON SEQUENCE reviews_id_seq FROM c2n_user;